/**
 * This class is generated by jOOQ
 */
package com.grafmap.infrastructure.persistence;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Grafmap extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 461408501;

	/**
	 * The singleton instance of <code>grafmap</code>
	 */
	public static final Grafmap GRAFMAP = new Grafmap();

	/**
	 * No further instances allowed
	 */
	private Grafmap() {
		super("grafmap");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE);
	}
}
