/**
 * This class is generated by jOOQ
 */
package com.grafmap.infrastructure.persistence;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>grafmap</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.grafmap.infrastructure.persistence.tables.records.FavoritePlaceRecord> KEY_FAVORITE_PLACE_PRIMARY = UniqueKeys0.KEY_FAVORITE_PLACE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.grafmap.infrastructure.persistence.tables.records.FavoritePlaceRecord> KEY_FAVORITE_PLACE_PRIMARY = createUniqueKey(com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE, com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE.ID);
	}
}
