/**
 * This class is generated by jOOQ
 */
package com.grafmap.infrastructure.persistence;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in grafmap
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table grafmap.favorite_place
	 */
	public static final com.grafmap.infrastructure.persistence.tables.FavoritePlace FAVORITE_PLACE = com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE;
}
