/**
 * This class is generated by jOOQ
 */
package com.grafmap.infrastructure.persistence.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FavoritePlaceRecord extends org.jooq.impl.UpdatableRecordImpl<com.grafmap.infrastructure.persistence.tables.records.FavoritePlaceRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -577636194;

	/**
	 * Setter for <code>grafmap.favorite_place.id</code>. 
	 */
	public void setId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>grafmap.favorite_place.id</code>. 
	 */
	public java.lang.String getId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>grafmap.favorite_place.user_id</code>. 
	 */
	public void setUserId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>grafmap.favorite_place.user_id</code>. 
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>grafmap.favorite_place.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>grafmap.favorite_place.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>grafmap.favorite_place.category</code>. 
	 */
	public void setCategory(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>grafmap.favorite_place.category</code>. 
	 */
	public java.lang.String getCategory() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>grafmap.favorite_place.latitud</code>. 
	 */
	public void setLatitud(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>grafmap.favorite_place.latitud</code>. 
	 */
	public java.lang.String getLatitud() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>grafmap.favorite_place.longitud</code>. 
	 */
	public void setLongitud(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>grafmap.favorite_place.longitud</code>. 
	 */
	public java.lang.String getLongitud() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE.CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE.LATITUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE.LONGITUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCategory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getLatitud();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLongitud();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FavoritePlaceRecord
	 */
	public FavoritePlaceRecord() {
		super(com.grafmap.infrastructure.persistence.tables.FavoritePlace.FAVORITE_PLACE);
	}
}
